const DEFAULT_LIST_INDENT = 0.5;

const HEADER_COUNTER_DELIMITER = "．";

const HEADER_ALIAS_DELIMITER = ".";
const ORDERED_LIST_COUNTER_END = "）";

const UNORDERED_LIST_BULLET_SIGN = "・";

export {
  DEFAULT_LIST_INDENT,
  HEADER_COUNTER_DELIMITER,
  ORDERED_LIST_COUNTER_END,
  HEADER_ALIAS_DELIMITER,
  UNORDERED_LIST_BULLET_SIGN,
};
